ish-app/ish

README.md

This includes small changes required to get the setup working on a brand
new development machine.

Add more detailed setup guide to README

---

kernel/calls.c
kernel/calls.h
kernel/group.c

added syscall 147 - getsid

---

README.md

To make it a little easier for the people :smirk:

Link the Alpine download page in the README

---

README.md

Made a small edit to make the README nicer. If you click on the logo, it opens the homepage, https://ish.app

added preview image to the README

---

.travis.yml

I've moved the existing Linux build to a build matrix and added a new entry to build the iOS app.

Add macOS support to .travis.yml

---

tools/fakefsify.py

Some distributions such as Ubuntu contains hard links in the tar
file. Hard links share the same inode as a previously seen file.

fakefsify: handle hard links

---

.travis.yml
fs/dev.c
fs/mem.c
fs/mem.h
kernel/random.c
kernel/random.h
meson.build

supercedes https://github.com/tbodt/ish/pull/178
reorganizes memory devices, adds device handlers for /dev/random, zero, full

/dev/[u]random implementation

---

app/Assets.xcassets/Hide Keyboard.imageset/Contents.json
app/Base.lproj/Main.storyboard
app/TerminalViewController.m

Also use a single scale for the vector image and fix a bug with setting the tint color

Fix highlight for hide keyboard button

---

app/UserPreferences.m

I have zero idea if this works as there is literally no way for me to test it. Please somebody with a mac and Xcode compile it and tell me if it works! Thanks
Suggestion from this by: sebastianpc#4420 on Discord

Added Green on Dark

---

app/AppDelegate.m

Fixes #173 by allowing IPv6 DNS addresses

 Updated AppDelegate.m so that IPv6 addresses are used for DNS

---

app/AppDelegate.m

I haven't tested this at all, so it would be nice if you could do it for me (or wait for me to be able to build this again).

A memory corruption issue was addressed with improved memory handling.

---

iSH.xcodeproj/project.pbxproj

https://alpinelinux.org/posts/Alpine-3.9.0-released.html

Upgrade Alpine to 3.9.0

---

iSH.xcodeproj/project.pbxproj

Change short lists available at: [https://www.alpinelinux.org/posts/Alpine-3.9.2-released.html](https://www.alpinelinux.org/posts/Alpine-3.9.2-released.html) & [https://www.alpinelinux.org/posts/Alpine-3.9.1-released.html](https://www.alpinelinux.org/posts/Alpine-3.9.1-released.htmll)

Upgrade Alpine to 3.9.3

---

kernel/exit.c

remove status argument from halt_system

---

iSH.xcodeproj/project.pbxproj

Change short list available at: https://alpinelinux.org/posts/Alpine-3.9.4-released.html

Upgrade Alpine to 3.9.4

---

kernel/init.c
xX_main_Xx.h

```bash
$ echo "whoami" | ./ish -f ../alpine /bin/sh
whoami
/ # whoami
root
/ # ^[[20;5R
```
Program then hangs until interrupted.
```bash
$ echo "whoami" | ./ish -f ../alpine /bin/sh
root
$
```
Program stops!
This will be useful for automating running iSH for scripted tests.

If stdin is not a tty, inherit stdin/stdout/stderr.

---

app/Terminal.m

Changed the request for webView iOS13b4. Now it shows the interface again.

Changed webView for iOS13b4

---

iSH.xcodeproj/project.pbxproj
tests/e2e/e2e.bash

https://alpinelinux.org/posts/Alpine-3.10.0-released.html

Upgrade Alpine to 3.10.0

---

jit/gadgets-x86_64/misc.S

Want to get eyes on this before I patch in a third branch for immediates

simplify vec gadget branching

---

app/AppDelegate.h
app/AppDelegate.m
app/Info.plist
app/SceneDelegate.h
app/SceneDelegate.m
app/Terminal.h
app/Terminal.m
app/TerminalView.m
app/TerminalViewController.h
app/TerminalViewController.m
app/terminal/term.js
fs/pty.c
fs/tty.c
fs/tty.h
iSH.xcodeproj/project.pbxproj
kernel/init.c
kernel/init.h
xX_main_Xx.h

This is a pretty big change so I'd like some help testing it before I merge. If you're interested, please build and test this PR and make sure nothing weird or unexpected happens.
cc @NoahPeeters

Multiwindow

---

fs/fd.h
fs/proc.c
fs/real.c
fs/tty.c
kernel/fs.c
kernel/futex.c
kernel/signal.h

Written largely in GNU Nano and with minimal testing; in addition to the usual scrutiny I would check formatting if I were you.

Fix pread/pwrite; make read/write be optional

---

README.md
app/AboutViewController.m

with the impending ~~end of the world~~ repo move, I have updated the links to it. yes, I ignored the changelog. I presume you’ll update the link when you update the changelog?

update repo links

---

app/iOSFS.m

Terminate mount after dismissing a document picker

---

app/AppGroup.h
app/AppGroup.m
app/Base.lproj/About.storyboard
kernel/exec.c
kernel/exit.c
kernel/fork.c
kernel/task.c
util/sync.h

Fix things

---

app/terminal/term.js

Turn on Ligatures

---

LICENSE.md

Agree to relicense my contributions

---

LICENSE.md

Here's my agreement for my part of the code base :)

Add license agreement

---

LICENSE.md

For whatever is still left in there :)

Relicensing agreement

---

LICENSE.md

Jumping on the license-wagon 

---

app/Roots.storyboard
app/RootsTableViewController.m

Use viewDidLoad over awakeFromNib for KVO init

---

app/APKServer.h
app/APKServer.m
app/AppDelegate.m
deps/aports/.gitignore
deps/aports/download-repos.py
deps/aports/odrs.py
deps/aports/update-archive.sh
iSH.xcconfig
iSH.xcodeproj/project.pbxproj

Add apk server using ODRs

---

README_ZH.md

Update chinese readme and fix some translation error.

README: update chinese readme

---

LICENSE.md

MatthewMerrill GPL2 license agreement

---

LICENSE.md

Hey,
> I'm working on replacing the iSH syscall handling code with a port of the actual Linux kernel
That sounds very exciting! 🥳 
I've added my name and email to the LINCENSE.md file to show that I accept the relicensing 👍

Accepting relicensing

---

LICENSE.md

Relicense as GPLv2

---

LICENSE.md

I agree with @tbodt on relicensing to GPLv2 (#1303).
My contributions are [these](https://github.com/ish-app/ish/pulls?q=is%3Apr+author%3Akkk669+is%3Aclosed).

Add my name to LICENSE.md

---

app/AboutAppearanceViewController.m
app/Base.lproj/About.storyboard
app/Base.lproj/Terminal.storyboard
app/TerminalViewController.m
app/UserPreferences.h
app/UserPreferences.m

Not a one commit wonder
Addresses issue https://github.com/ish-app/ish/issues/620 with a complete implementation.

Add Ability to Toggle Status Bar

---

kernel/calls.c

Stub faccessat2

---

README_KO.md

Hi, I appreciate your application.
Your sacrifices made while working with macros and linker errors must be known to the world.
So I created the Korean version of your README.md.
Joking aside though thank you for creating and maintaining this app!

Korean translation of README.md

---

app/TerminalViewController.m

Revert the terminal switching key command modifiers

---

app/AppDelegate.m
deps/libarchive.xcodeproj/project.pbxproj
fs/proc.h
fs/proc/entry.c
fs/proc/ish.c
fs/proc/pid.c
fs/proc/root.c
iSH.xcodeproj/project.pbxproj
iSH.xcodeproj/xcshareddata/xcschemes/Screenshots.xcscheme
iSH.xcodeproj/xcshareddata/xcschemes/iSH+Linux.xcscheme
iSH.xcodeproj/xcshareddata/xcschemes/iSH.xcscheme
iSH.xcodeproj/xcshareddata/xcschemes/ish-cli.xcscheme
meson.build

Create /proc/ish and populate /proc/ish/version to start with.

Add /proc/ish

---

fs/mount.c
fs/proc/root.c
kernel/fs.h

Welcome to Alpine!
You can install packages with: apk add
You may change this message by editing /etc/motd.
MacBook-Pro:# cat /proc/filesystems
nodev real
nodev proc
nodev devpts
nodev tmpfs
nodev ios
nodev ios-unsafe
MacBook-Pro:#

Add /proc/filesystems

---

README_ZH.md

Update:
- Fix mistaking port as a linux pkg manager in requirements installation section
- Add contents of project build settings in build for iOS section
- Improve the description of `DEFAULT_CHANNEL` in logging section
- Add white space between character and letter/number

Update: README_ZH.md

---

app/Base.lproj/About.storyboard

Now says "Keep Screen Turned On" instead of "Disable Screen Dimming", resolving #1237.

Rename screen dimming label

---

app/AboutAppearanceViewController.m
app/AboutNavigationController.m
app/AboutViewController.m
app/Base.lproj/About.storyboard
app/TerminalView.h
app/TerminalView.m
app/TerminalViewController.m
app/Theme.h
app/Theme.m
app/ThemeViewController.h
app/ThemeViewController.m
app/ThemesViewController.h
app/ThemesViewController.m
app/UserPreferences.h
app/UserPreferences.m
app/terminal/term.js
fs/proc/ish.c
fs/proc/ish.h
iSH.xcodeproj/project.pbxproj

Most of the stuff you'd want: system appearance matching, default themes, custom user-specified themes, procfs and documents directory integration.

Custom theme support

---

app/AboutAppearanceViewController.m
app/RootsTableViewController.m
app/ThemesViewController.m

These fell out of additional manual testing and user feedback for some recent changes.

Miscellaneous fixes

---

fs/proc/pid.c

This PR adds `/proc<pid>/cwd`.
```
/root
/hoge/huga# touch x.txt
/hoge/huga# touch y.txt
/hoge/huga# echo $$
8
/hoge/huga# ls /proc/8/cwd
x.txt  y.txt
/hoge/huga# ls -l /proc/8 | grep cwd
lrwxrwxrwx    0 root     root             0 Jan  1  1970 cwd -> /root/hoge/huga
```

add /proc/<pid>/cwd

---

app/UserPreferences.m

Register friendly preferences with NSUserDefaults

---

emu/decode.h

Add stub implementations for movs to/from fs

---

app/UserPreferences.m

Fix validation of cursor style, color scheme

---

app/Theme.m

For example, directories. Fixes #2343

Skip items in themes directory with no data

---

app/FileProvider/FileProviderItem.m
fs/fake-db.c
fs/fake-db.h
fs/fake.c
fs/generic.c
fs/inode.c
fs/real.c
iSH.xcodeproj/project.pbxproj
linux/fakefs.c
meson.build
tools/fakefs.c
tools/meson.build
util/fchdir.c
util/fchdir.h
util/sync.h

https://gist.github.com/tbodt/2dd95b6353ed1b717e834fc3ae2d2adf

Named pipe fixes
