ish-app/ish

- README.md
I'm trying to build this and realized it needs Yarn to build, which is not something that I have installed. I thought it might be useful to list this as a build requirement to help those like me who don't have it.
Anyways, onto figuring out how to tell deasync to target iOS instead of x86_64 through gyp…
> List Yarn as a dependency for building

- tools/fakefsify.py
When the user doesn't specify all of the arguments needed for `fakefsify.py` he get's a backtrace, which can be a little irritating.
Added a little usage information on how to use this script.
> Add usage information instead of backtrace

- kernel/calls.c
- kernel/time.c
- kernel/time.h
I wanted to poke around the internals of iSH, so I thought I'd "get my feet wet" by implementing a simple, obsolete, and mostly useless system call to get a taste of project development. Please let me know if there's anything you'd like changed; I've tried to model this after the other syscall implementations.
Just as a heads up, since this confused me for a while: if you want to test this, you'll need to use `syscall(SYS_gettimeofday, …)` directly instead of `gettimeofday` because musl's version just calls `clock_gettime`.
> Implement gettimeofday

- fs/fd.h
- iSH.xcodeproj/project.pbxproj
- kernel/errno.h
- kernel/fs.h
- kernel/resource.h
- kernel/signal.h
Use `(void)` instead of `()` for function prototypes, except for `fdtable_new` which actually takes an `unsigned`. Also, tell Xcode that this project uses spaces for indentation–if you don't, mine will keep trying to insert tabs everywhere because that's what my global configuration is set to.
> Make Xcode happy

- emu/decode.h
This fixes application startup on Ubuntu. #107
----
This, along with [a hack](https://github.com/zhuowei/ish/commit/b99dfb26c1a6afbfd401e05c045b8426e73c2e3a) to make all unimplemented syscalls return _ENOSYS, is enough to start Ubuntu's /bin/bash.
Some questions:
1. I tried to model this after the regular GS handling code. Is the goto correct? It should restart decoding on the next prefix.
2. I think switching the order of these prefixes is [technically allowed](https://stackoverflow.com/questions/7197282/order-for-encoding-x86-instruction-prefix-bytes); are there any apps in the wild that has the GS prefix before LOCK?
3. Not related to this change, but : why do unimplemented syscalls raise a signal? Linux itself just [returns _ENOSYS](https://github.com/torvalds/linux/blob/master/kernel/ …
> decode: handle GS prefix after LOCK prefix

- emu/decode.h
This is just a copy-paste of the same code as the already implemented `xchg odi, oax` for the rest of the registers.
> decode: implement remaining xchg reg32, oax instructions

- app/TerminalView.m
The current `-[TerminalView canPerformAction:withSender:]` breaks a bunch of things because it returns `NO` for a bunch of commands we can actually handle, such as copying or `handleKeyEquivalent:`.
> Make copy/arrow keys/escape/a bunch of other stuff work again

- emu/decode.h
- emu/interp/fpu.h
- jit/gen.c
It's just aliased to fucomi for now.
This fixes launching apt in a Ubuntu 18.04.1 root fs.
> decode: implement fcomi

- emu/decode.h
- emu/float80.c
- emu/float80.h
- emu/fpu.c
- emu/fpu.h
- emu/interp/fpu.h
- jit/gen.c
There's no interpreter version yet.
----
This fixes the illegal instruction error when running `apt update` in a Ubuntu rootfs.
I haven't tested if this is accurate. `apt update` runs this instruction to show download progress. Since `select` with more than one fd doesn't work, it's stuck at 0%, so I can't tell if the instruction is broken.
> decode: implement fxam

- fs/sock.c
- fs/sock.h
Requests for raw sockets for ICMP now create a DGRAM socket which allows ping to work.
Fixes #76
> Allow fake ICMP raw sockets (ping working)

- fs/sock.c
- fs/sock.h
Implementation of the `recvmsg(3)` socketcall and some socket flags and sockopts for `traceroute`.
`sendmsg(3)` can be implemented the same way, the `msghdr` and child struct operations should then be moved to own functions.
`traceroute` freezes at some point for some hosts, though i don't know if this could be busybox's traceroute implementation.
Fixes #200
> Implement recvmsg socketcall (fixes traceroute)

- xX_main_Xx.h
Should this check be done for stderr too?
> If stdout isn't a tty either, fall back to stdio

- .github/FUNDING.yml
'paypal' is not a valid funding platform, so I guess it should just be a custom link.
> Fix FUNDING.yml PayPal link

- app/AppDelegate.m
`zero_dev` and `full_dev` were already implemented, but devices weren't created.
> Create /dev/zero and /dev/full on start

- jit/frame.h
- jit/gadgets-aarch64/control.S
- jit/gadgets-x86_64/control.S
- jit/gen.c
- jit/gen.h
- jit/jit.c
- jit/offsets.c
This implements the return cache optimization for JIT mode.
The technical details of this optimization can be read at https://github.com/wishstudio/flinux/wiki/Dynamic-Binary-Translation#return-handling.
The implementation creates a new gadget named "call_postamble" and appends it after each call gadget. It checks whether the return address is correct and links to the actual successor code.
The actual performance improvement depends on application being run. I have observed run time reduction up to 15% on aarch64. No performance regression has been observed.
> Implement return cache optimization.

- .travis.yml
- emu/memory.c
- emu/memory.h
- jit/jit.h
- meson.build
- meson_options.txt
`-Djit=true` => `-Dengine=jit`
`-Djit=false` => `-Dengine=interp`
> Migrate `-Djit=true` option to `-Dengine=jit`.

- kernel/mmap.c
Fixes a thread sanitizer warning.
> Replace read lock with write lock in mm_copy

- iSH.xcodeproj/project.pbxproj
- tests/e2e/e2e.bash
https://alpinelinux.org/posts/Alpine-3.11.0-released.html & https://alpinelinux.org/posts/Alpine-3.11.2-released.html
Due to a problem with Xcode and my 10 year old Macbook, I was unable to test this. I did, however, update Alpine manually on my iPhone and I didn't experience any errors.
> Upgrade Alpine to 3.11.2

- kernel/calls.c
- kernel/calls.h
- kernel/getset.c
This provides the simple part of fixing #47, as GDB makes system call 136 `sys_personality` with arguments `0x0000` (set and return value for Linux) and `0xffffffffff` (get value). In any other case error code -1 is returned. See http://man7.org/linux/man-pages/man2/personality.2.html
> Add syscall 136 personality

- fs/lock.c
- kernel/fs.h
Lock flags fix for #628 (kerberos commands return "Bad file descriptor")
> Fix lockfile flag checks

- app/iOSFS.m
I added `picker.allowsMultipleSelection = YES` when it's running on iOS 12 or earlier. This enables the iOSFS to work on iOS 12 or earlier. Besides, behaviors on iOS 13 will not be changed.
If multiple directories are selected, the first one is mounted as you can see on the video below.
Fixes #700
> Make iOSFS work on iOS 11 and 12 (#700)

- emu/cpuid.h
- meson.build
- meson_options.txt
This does not signify that SSE2 is fully supported or supported enough
to run any particular programs. Rather, it is used to signal to programs
running in iSH to behave as if SSE2 is supported so that the programs
can be allowed to crash on the lines where the SSE2 support is lacking.
> Add meson option for declaring SSE2 support.

- emu/cpu.h
- emu/tlb.c
- emu/tlb.h
- jit/jit.c
- kernel/calls.c
- kernel/task.c
- kernel/task.h
- main.c
- tools/ptraceomatic.c
- tools/unicornomatic.c
There was a deadlock when cpu_run called cpu_step_to_interrupt with mem
read-locked, and it would write-lock mem to clean up jetsam.
> Fix locking issues with CPU refactor

- deps/libarchive.xcodeproj/project.pbxproj
1.  The headers build phase was causing the 'archive' build to produce
an Xcode generic archive rather than an application archive during
packaging. This PR removes that build phase from the libarchive
subproject.
> Remove the headers build phase from libarchive

- tests/e2e/e2e.bash
The script now does not fail if no tests were run. The crash occurred because the script tried to divide by $NUM_TOTAL even though this would be 0.
fixes #744
> Updated e2e.bash

- app/AboutViewController.m
- app/Base.lproj/About.storyboard
I thought it could look nice to have version info somewhere, so I added it to the bottom of the About screen ¯\\\_(ツ)_/¯
<details>
<summary>Here's what it looks like</summary>
</details>
Works fine on iPhone and looks correct in the iPad simulator as well.
> Add a version label to the About view

- app/TerminalViewController.m
- app/UserPreferences.m
The documentation for UIStatusBarStyleDefault says the result has dark
text, but that's a lie since iOS 13. It is now whatever color goes with
the system appearance. Use UIStatusBarStyleDarkContent instead if we're
on iOS 13 and specifically want dark text.
> Fix color of status bar in dark mode

- xcode-meson.sh
Invoking clang directly through the Xcode toolchain (which happens because
Xcode sets the PATH) instead of through /usr/bin/clang seems to break SDK
autodetection. Use xcrun to get around this.
Fixes #913
> Fix build on Apple Silicon hosts

- LICENSE.md
I hereby accept the relicence of [iSH](https://github.com/ish-app/ish) from GPLv3 to GPLv2.
This should be the name and email used for my git contributions. If not, I can change it accordingly.
> Accepted relicense

- LICENSE.md
This is to confirm that I agree with relicensing my contributions to iSH under the GPLv2.
> GPLv2: Christopher Albert

- tools/staticdefine.sh
fixes #1460, now builds and runs fine on ubuntu 20.04 (which doesn't ship with python2)
> Use python3 during build

- kernel/calls.c
This fixes #1324 on master which is currently running alpinelinux v3.14
> Stub missing syscall 364, also added comment for syscall 383

- README.md
- README_KO.md
- README_ZH.md
This is probably the intended example line. Not sure if the quote when copied&pasted may fail, just proposing this fixup to be safe.
> Docs: Fix readme cli quoting

- kernel/calls.c
MacBook-Pro:~# dmesg | uniq
8(login) stub syscall 383
10(ash) stub syscall 383
11(ash) stub syscall 383
9(ash) stub syscall 383
15(ls) stub syscall 383
9(ash) stub syscall 383
17(sshd) stub syscall 383
19(sshd) stub syscall 364
20(sshd) stub syscall 383
22(sshd) stub syscall 383
23(ash) stub syscall 383
24(ash) stub syscall 383
22(ash) stub syscall 383
27(apk) stub syscall 383
28(busybox-1.33.1-r) stub syscall 383
22(ash) stub syscall 383
> Print the process name as well as the pid on 'stub syscall'

- jit/gadgets-aarch64/memory.S
- jit/gadgets-aarch64/misc.S
Like #1429, but less wrong.
My prior PR misinterpreted certain paragraphs of Intel's processor documentation. Unaligned `lock cmpxchg8b` maintains atomicity *regardless* of alignment; this is not emulatable with ARM atomics alone. Properly emulating this requires a complicated locking setup that would almost certainly harm the performance of well-behaved x86 processes. In fact, I'm pretty sure the prior PR *never worked* - I've noticed this crash doesn't always occur when you launch `mariadbd`; and it's entirely possible that I was just getting very lucky with heap allocations that just so happened to align whatever packed structs are there.
So, instead, here's a new PR that triggers a segfault on unaligned atomic access. This will keep the user from losing any other work they might have …
> Segfault the guest process when we encounter an unaligned atomic cmpxchg8b

- app/AboutAppearanceViewController.m
- app/AboutExternalKeyboardViewController.m
- app/AboutNavigationController.m
- app/AboutViewController.m
- app/AppDelegate.m
- app/TerminalView.m
- app/TerminalViewController.m
- app/UserPreferences.h
- app/UserPreferences.m
- fs/proc.c
- fs/proc.h
- fs/proc/entry.c
- fs/proc/ish.c
- fs/proc/ish.h
- fs/proc/pid.c
- fs/proc/root.c
- iSH.xcodeproj/project.pbxproj
High level design:
* User defaults are now available via /proc/ish/defaults and /proc/ish/.defaults. The latter is "all" preferences and the former symlinks into it for "friendly" names and to indicate that these are preferences we explicitly support you changing.
* Removing the file, as well as reading and writing to it is supported. This is roughly equivalent to reseting the preference, getting it, and setting it.
* Preferences are exposed via JSON fragments.
> Expose user defaults via /proc/ish

- kernel/calls.c
These syscalls have fallbacks in musl which we do implement but they are only invoked after they return ENOSYS, which fills dmesg with lots of spam.
> Replace chatty syscall stubs with silent variant

- fs/path.c
- xX_main_Xx.h
Running ./ish with no command line argument resulted in a segmentation fault.
On line 106 in xX_main_Xx.h, the first argument of do_execve() received a nullptr, but no adequate checks were provided to handle nullptr. The nullptr is then passed into strcmp(), which resulted in undefined behaviors (segfaulted on my system).
So a check for (path == NULL) was provided in path_normalize(), so _ENOENT can be returned instead of undefined behavior from passing NULL into strcmp().
> added nullptr check (previously segfaulted)

- deps/meson.build
- tools/meson.build
- vdso/meson.build
Fixes the following:
```
WARNING: You should add the boolean check kwarg to the run_command call.
It currently defaults to false,
but it will default to true in future releases of meson.
See also: https://github.com/mesonbuild/meson/issues/9300
```
and
```
WARNING: find_library('libarchive') starting in "lib" only works by accident and is not portable
```
> meson: fix warnings

- app/AccessibilityFixes.m
- app/App.xcconfig
- app/hook.c
- app/hook.h
- iSH.xcodeproj/project.pbxproj
This is a workaround for https://bugs.webkit.org/show_bug.cgi?id=249976, which should fix #1937.
There's a couple of things going on here that are probably worth noting:
* We rely on some things from the macOS SDK that happens to not be copied over the the iPhone one.
* These are part of the platform ABI. In once case we use mig but could drop it in the future and use the generated files directly, if it becomes necessary. In another case use use a function from a header that Apple seems to have forgotten to include in the SDK. We can just ask for them to include it, and even if it goes away it isn't critical to anything.
* We need to parse the shared cache for symbols.
* For space reasons Apple removes symbols from the address space that aren't exported. We need to read them out again …
> Patch out web view focus stealing first responder

- app/AppDelegate.m
- app/ExceptionExfiltrator.h
- app/ExceptionExfiltrator.m
- app/main.m
- iSH.xcodeproj/project.pbxproj
Apple's crash reports don't contain exception name/reason information. We can get this back in a roundabout way by constructing a fake backtrace and encoding the exception information into that.
> Encode exceptions into the crash log

- fs/tty.c
- fs/tty.h
I have made modifications to TIOCGPGRP for the pty master.
Currently, if the tty of the master is not set as the controlling terminal for the process group to which the current process belongs, it results in an error. However, the actual behavior in Linux is that when a file descriptor of the pty master is specified, it sets the process group ID of the controlling terminal to the corresponding slave when available. Therefore, for the pty master, I have made the modification to return the fg_group of the tty set as 'other.'
Furthermore, I have corrected the name from TIOCGPRGP, which seems to be a typo, to TIOCGPGRP.
> fix tiocgpgrp for pty master

- kernel/fs.c
- kernel/log.c
- kernel/poll.c
- kernel/time.h
- tools/meson.build
- xX_main_Xx.h
`mosh` almost works, but it has weird unpredictable 1-30 second lag on text input that is quite incredibly annoying.
I ran this down to a fairly simple oversight:  `pselect()` takes a `timespec` for the timeout value, but that was getting passed unchanged to the iSH `select()` implementation which takes a `timeval`.
It looks like a fix was made for #711 earlier that sort of worked; this probably fixes the real underlying problem with Emacs.  That change clamped the excessively big nanosecond values to be +1 second, but Mosh was still badly affected.
This will probably clear up other mysterious lags in other applications.
There's a couple of other minor fixes I needed to get the CLI build working and logging, too.
> Fix bad timeout values in `pselect()` (which broke mosh)

- fs/proc/ish.c
`find /proc` segfaults on CLI iSH.
The CLI iSH does not implement some callouts that iSH's procfs provides for the GUI, and the procfs does not check that these callouts actually exist.  This fixes that.
> Avoid crashes on /proc/ish from CLI build

- README.md
- README_KO.md
- README_ZH.md
- fs/pty.c
- fs/tty.c
- fs/tty.h
- ish-lldb.lldb
- kernel/exit.c
- kernel/log.c
There's two big things in here.
When running `mosh --local 0`, I found that `mosh-server` would never terminate on iSH.  It was waiting for the master side of its pty to close.  Most applications that use ptys use other methods to detect child termination, but `mosh-server` expects that the pty master will act as a closed file after the last program on the pty slave exits-- any waiting reads should return immediately with 0 bytes, and further read calls should return EOF.  This is what pipes and sockets do, of course.  iSH master ptys stayed in the read call forever, even though the pty slave was gone.  This fixes that and ends up better separating generic tty code from pty slaves from pty masters too.
`dtach` behaves similarly and the fix helps it too.
After I fixed that, I found that …
> Fix pty close behavior, signals at exit

- app/AppDelegate.m
- app/UserPreferences.h
- app/UserPreferences.m
Users really hate that we put "localhost" in their prompt as a result of iOS 16 anti-fingerprinting obfuscating the device name. We already have a mechanism for overriding this that we use for App Store screenshots, so we might as well make it official and expose it for those that care.
The logic for what the actual uname hostname is as follows:
* If the user sets the preference, use that.
* On iOS <16, if the preference is unset, use what real uname returns.
* On iOS 16+, use UIDevice.name. This at least changes "localhost" to something like "iPad".
> Promote hostname override to a friendly preference 

- app/FileProvider/FileProviderEnumerator.m
- app/FileProvider/FileProviderExtension.m
- app/FileProvider/FileProviderItem.m
- fs/fake-db.c
- fs/fake-db.h
- fs/fake.c
- linux/fakefs.c
Fun quirk of sqlite is that if you BEGIN DEFERRED and then do a read statement and then another process concurrently does a write and then the first process does a write statement on the same transaction, it will immediately return SQLITE_BUSY because it's impossible to do a write against a past version of the database. To fix this we need to use BEGIN IMMEDIATE to take a write lock upfront on any transaction that will need to write.
> Make sure to take sqlite write locks upfront
